# Generated by Django 5.2.17 on 2026-10-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pipeline', models.CharField(max_length=20)),
                ('hit_rate', models.FloatField()),
                ('avg_groundedness', models.FloatField()),
                ('cases', models.IntegerField()),
                ('git_sha', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pipeline', models.CharField(db_index=True, max_length=20)),
                ('role', models.CharField(default='public', max_length=10)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True)),
                ('blocked', models.BooleanField(default=False)),
                ('findings', models.CharField(blank=True, max_length=200)),
                ('groundedness', models.FloatField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('source_ids', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
