# Generated by Django 5.2.17 on 2026-10-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filename', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=10)),
                ('acl', models.CharField(default='public', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.upload')),
            ],
            options={
                'ordering': ['upload_id', 'idx'],
            },
        ),
    ]
